lib/onlyoffice_documentserver_testing_framework/test_instance_docs.rb
See error in palladium:
/product/4/plan/687/run/49902/result_set/1631395
=> Fix issue with using old webdriver while running several tests

lib/onlyoffice_documentserver_testing_framework/selenium_wrapper.rb
Allow to set variables to nil, but keep this work
=> Simplify check of frame variables is defined

lib/onlyoffice_documentserver_testing_framework/selenium_wrapper.rb
See:
https://github.com/ONLYOFFICE/sdkjs-plugins/issues/68
Bug is minor, so I think it's better to ignore this error
=> Add workaround for youtube insert minor bug

lib/onlyoffice_documentserver_testing_framework/selenium_wrapper/selenium_wrapper_js_errors.rb
Previous variant cause that root directory
counted as project root dir in wihch gem required.
=> Change method to require file in Gem

.travis.yml
This cause dialog for override gem in `ruby-head`
like this and hangup for 10 minutes:
```
$ gem update --system
Updating rubygems-update
Fetching rubygems-update-3.1.0.pre2.gem
Successfully installed rubygems-update-3.1.0.pre2
Installing RubyGems 3.1.0.pre2
Successfully built RubyGem
Name: bundler
Version: 2.1.0.pre.2
File: bundler-2.1.0.pre.2.gem
bundler's executable "bundle" conflicts with /home/travis/.rvm/rubies/ruby-head/bin/bundle
Overwrite the executable? [yN]
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
=> Remove gem update system

lib/onlyoffice_documentserver_testing_framework/selenium_wrapper/selenium_wrapper_js_errors/ingored_errors.list
This error happens almost in any html file with internal
image, so just ignore it
Files like this:
https://github.com/ONLYOFFICE/testing-documentserver/blob/04631758b52c5906498548c36b802ea5219f2bb9/data/data_files/formats/Doc_Specification.html
=> Change ignored error for 404 error

Changelog.md, lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_editor/doc_editor_windows/txt_options.rb, lib/onlyoffice_documentserver_testing_framework/test_instance_docs/management.rb
It's more logical, since in value is nil - there is no
changes to interface performed
=> Change `TxtOptions#txt_options=` default param to nil

lib/onlyoffice_documentserver_testing_framework/selenium_wrapper/selenium_wrapper_js_errors/ignored_errors.list
Seems there is line number after `en-US` string
in current version of chrome
See:
https://bugzilla.onlyoffice.com/show_bug.cgi?id=43989
=> Change autofocus error for youtube plugin

lib/onlyoffice_documentserver_testing_framework/test_instance_docs/management.rb
Since v6.0.0 of DocumentServer
round loading mask start to appear not instantly
but after some timeout specified in
https://github.com/ONLYOFFICE/web-apps/commit/a7988dc7ec1f1151ef2c204677d1746a65e39132#diff-eee9ef38f1b712adf8bcc94c29de431aR127
=> Wait for loading mask to start

.github/workflows/ruby.yml, CHANGELOG.md
From [yesterday](https://github.com/ruby/ruby/commit/21c62fb670b1646c5051a46d29081523cd782f11) ruby 2.8 is ruby 3.0 and some gems just can't be installed on it
Until at least https://github.com/simplecov-ruby/simplecov-html/commit/6567856c6940e285bbb70cce98edca60c7dfefdd2 is released
=> Allow CI failures on ruby-head

CHANGELOG.md, lib/onlyoffice_documentserver_testing_framework/selenium_wrapper/selenium_wrapper_js_errors/ignored_errors.list
All happened in this test:
https://github.com/ONLYOFFICE/testing-documentserver/blob/468f8d1219d7f1e430c4b2b41c79fa6b168831e0/spec/modules/spreadsheets/spreadsheet_editor/autosave/collect_version_spec.rb#L9
Error like this:
```
"https://nacho.teamlab.info/UserControls/Management/AuthorizationKeys/img/smsc.svg - Failed to load resource: the server responded with a status of 502 ()"https://nacho.teamlab.info/UserControls/Management/AuthorizationKeys/img/firebase.svg - Failed to load resource: the server responded with a status of 502 ()"
"https://nacho.teamlab.info/UserControls/Management/AuthorizationKeys/img/bitly.svg - Failed to load resource: the server responded with a status of 502 ()"
"https://nacho.teamlab.info/UserControls/Management/AuthorizationKeys/img/yahoo.svg - Failed to load …
```
=> Add new error to ignored list

lib/onlyoffice_documentserver_testing_framework/test_instance_docs/management.rb
This should only filter out document editor help frame
Not editors on portal helpcenter.onlyoffice.com
Found by this test:
https://github.com/ONLYOFFICE/testing-onlyoffice/blob/bafbde7a883591e7498e9cd13651a9740ffd4c46/spec/site/multi_lang/functional/get_onlyoffice/site_registration_signin_spec.rb#L41
=> Fix default xpath for iframe

.github/workflows/ruby.yml, lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_test_site_functions.rb
Also increase start timeout, since latest version are slower to start
=> Use actual image -ee instead of deprecated -ie

lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_test_site_functions.rb
Since:
https://github.com/ONLYOFFICE/document-server-integration/pull/134
Not much changed in xpath, but design is completely new:
=> New design of test example were implemented on develop

CHANGELOG.md, Gemfile.lock, onlyoffice_documentserver_testing_framework.gemspec
Update onlyoffice_webdriver_wrapper
Without it tests cannot be run
=> Drop support of `ruby-2.4` since it's EOLed more than year ago

CHANGELOG.md, lib/onlyoffice_documentserver_testing_framework/test_instance_docs/management.rb
This was changed in DocumentServer v6.4
=> Support for waiting to load Mobile Editors

CHANGELOG.md, lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_test_site_functions.rb
Since:
https://github.com/ONLYOFFICE/testing-documentserver/pull/5285
It always ending with `/` so no need to add it in this method
=> Fix healthcheck url

CHANGELOG.md, lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_test_site_functions/doc_test_file_list/doc_test_site_file_list_entry.rb
This was changed in:
https://github.com/ONLYOFFICE/document-server-integration/commit/0ae02d8af9d6f3765d3ddf6cbef41640556c644e#diff-cb6c891b688e4abedba1cf56eeb95c384efd16e98ab9be44eaeef131633ee3dcR182
I don't think it's such important thing, so I will not add versioning
=> Fix order of comment and review mode

.github/workflows/ruby.yml, CHANGELOG.md, lib/onlyoffice_documentserver_testing_framework/selenium_wrapper.rb, onlyoffice_documentserver_testing_framework.gemspec
Method selenium_functions works on ruby 2.6 and fails on ruby 3.1 when the last argument looks like `option: value`
For example:
```
selenium_functions :click_on_locator, "#{@symbols_table_xpath}/div[#{number}]", false, count: 2
```
=> Fix compatibility issue with ruby 3.1

CHANGELOG.md, lib/onlyoffice_documentserver_testing_framework/selenium_wrapper.rb
Previous variant has `wait_element` instead of
`wait_until_element_visible`
And this case just timeout on wait_element without any error
if there is several elements with same xpath
But current variant is failing, since for example on page there is two
elements and only a second one visible, so
`wait_until_element_visible` is failing
I think proper way is not wait for any element at all and handle waiting
in some other place
=> `click_on_displayed_button` do not wait for button to appear

lib/onlyoffice_documentserver_testing_framework/selenium_wrapper/selenium_wrapper_js_errors/ignored_errors.list
In Chrome versions above 114. When downloading a file from a document server on an http connection, a warning: 'was loaded over an insecure connection. This file should be served over HTTPS.'
=> Exception warning in js console

CHANGELOG.md, lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_editor/doc_editor_top_toolbar/home_tab/editor_tab.rb
Tooltips for new features were added in https://github.com/ONLYOFFICE/web-apps/commit/6477b16040a44a865da28e0db1b4b662dff37da7
=> Add closing tooltips when open editor tab
