- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_editor/doc_editor_windows/txt_options.rb
- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/spreadsheet_editor/spreadsheet_windows/csv_option.rb
Changed in:
https://github.com/ONLYOFFICE/web-apps-pro/commit/bd1d3af79fce41cd5c0dca39f016309a66cba9cd
Use `*` to keep compatibility with both version
> Change xpath for window title element

- Changelog.md
- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_test_site_functions/doc_test_file_list/doc_test_site_file_list_entry.rb
Since:
https://github.com/ONLYOFFICE/document-server-integration/commit/1217de89b334638c8b6dfe5954f302c6d7b341ad
> Ability to get `DocTestSiteFileListEntry#only_fill_forms_mode_url`

- .rubocop_todo.yml
- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_test_site_functions.rb
- spec/doc_test_funtions/doc_test_functions_languages_spec.rb
Since:
https://github.com/ONLYOFFICE/document-server-integration/commit/d12897930c681d5749daee911904264f17f1cd9c
Fix https://github.com/ONLYOFFICE/testing-documentserver/issues/2993
> Add new languages to example page

- .travis.yml
Use travis addons system instead
> Remove manual installation of Google Chrome

- .travis.yml
Same as:
https://github.com/onlyoffice-testing-robot/onlyoffice_webdriver_wrapper/pull/168
> Fix installing error on chrome

- .travis.yml
- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_test_site_functions.rb
Problem in chromedriver see:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3164
More details at:
https://github.com/onlyoffice-testing-robot/onlyoffice_documentserver_testing_framework/pull/25#issuecomment-568912255
> Fix opening test example

- lib/onlyoffice_documentserver_testing_framework/selenium_wrapper/selenium_wrapper_js_errors/ignored_errors.list
From Speech plugin
See:
https://bugzilla.onlyoffice.com/show_bug.cgi?id=44620
> Add one more entry for ignored error

- lib/onlyoffice_documentserver_testing_framework/selenium_wrapper/selenium_wrapper_js_errors/ignored_errors.list
There are some error from yandex maps with with host
> Ignore all errors from yandex yastatic host

- lib/onlyoffice_documentserver_testing_framework/selenium_wrapper/selenium_wrapper_js_errors/ignored_errors.list
See:
https://bugzilla.onlyoffice.com/show_bug.cgi?id=44522#c5
> Ignore errors for wasm

- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/management.rb
Quad seems enough, but need more testing
> Waiting for mast for one second is not enough

- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/spreadsheet_editor/spreadsheet_windows/csv_option.rb
Xpath was override by super constructo
> Fix incorrect order of csv arguments

- CHANGELOG.md
- Rakefile
Fix `rake` task for release on GitHub Packages
> Release v0.1.1

- .github/workflows/ruby.yml
- .markdownlint.json
- CHANGELOG.md
- lib/onlyoffice_documentserver_testing_framework/selenium_wrapper/selenium_wrapper_js_errors/ignored_errors.list
Since update of Google Chrome to v85
this message add some more text
Original problem is described here:
https://bugzilla.onlyoffice.com/show_bug.cgi?id=43989
And probably will not fixed in future
> Update ignored error test

- CHANGELOG.md
- Gemfile.lock
- lib/onlyoffice_documentserver_testing_framework/version.rb
> Release v0.4.0

- CHANGELOG.md
- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_editor/doc_editor_top_toolbar.rb
- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_editor/doc_editor_top_toolbar/title_row.rb
- spec/onlyoffice_documentserver_testing_framework/title_row/title_row_document_name_spec.rb
> New method to get doc name `TitleRow#document_name`

- .github/workflows/ruby.yml
> Change order of CI check for faster fails

- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/management/password_protected_helper.rb
New button to show password was added to Protected File window in https://github.com/ONLYOFFICE/web-apps/commit/63232779e904a5d8aacb5a789ae5e2b1308c255c
> Change xpath for OK button in Protected File window

- CHANGELOG.md
- Gemfile.lock
- lib/onlyoffice_documentserver_testing_framework/version.rb
Changelog was missed in https://github.com/ONLYOFFICE-QA/onlyoffice_documentserver_testing_framework/pull/508
> Release v2.1.0

- CHANGELOG.md
> Add forgotten changelog

- .github/workflows/ruby.yml
- CHANGELOG.md
* Add ruby-3.4
* Remove ruby-3.0
> Actualize Rubies in CI

- CHANGELOG.md
- lib/onlyoffice_documentserver_testing_framework/test_instance_docs/management/update_links_helper.rb
Message text changed in https://github.com/ONLYOFFICE/web-apps/commit/86df4a1432793d9fa1b64b914dc3a68999a15f92
> Fix text of update links message
